import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '../components/navbar';
import Card from '../components/Card';
import Stripe from 'stripe';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ prices = [] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />

      <section className='container mx-auto'>
        <h1 className='text-4xl mt-4 text-center'>Our Products</h1>
        {/* <div className='mt-4 grid grid-cols-1 md:grid-cols-3 gap-4'>

          {data.map(product => <Product product={product} />)}
         
        </div> */}

        <div className='mt-8 grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8'>
          {prices.map(price => (
            <Card key={price.id} price={price} />
          ))}
        </div>
      </section>
    </>
  )
}


export async function getServerSideProps() {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY)
  const { data: prices } = await stripe.prices.list({
    active: true, // Only bring active prices (a product can have multiple prices)
    limit: 10,
    expand: ['data.product'],
  })

  return {
    props: {
      prices,
    },
  }
}